
services:
  server:
    build: ./server
    container_name: server_backend
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - ./server:/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - ./client:/node_modules
    stdin_open: true
    tty: true